### ISSUE TITLE
Dependent window

### ISSUE THREAD

**Issue by developer239** [HelpfulHuman/Redux-Session#4]
> node_modules\redux-session\dist\index.js:21
> [0]     adapter = (window.localStorage ? 'localStorage' : 'cookieStorage');
> [0]                ^
> [0] 
> [0] ReferenceError: window is not defined

**Comment by NickGlenn** [comment]
@developer239 Sorry I didn't see this issue until now.  Are you trying to use this library outside of the browser (aka, in a server-side environment)?

**Comment by developer239** [comment]
I am not sure but I guess that I was trying to use window in node environment.
