### ISSUE TITLE
Throttle should keep track of dirty state

### ISSUE THREAD

**Issue by patrick-mcdougle** [HelpfulHuman/Redux-Session#5]
I love that there's a throttle feature, but currently there's unexpected behavior with this. If I'm making a lot of changes to state within the 2 seconds, the state doesn't get persisted. I think a potential improvement would be to track if the state gets dirty during the throttle period, and persist one last time when the timer gets cleared. This will guarantee that all state gets persisted even if updates happen during the throttle period.

I'll try to work on a patch this weekend, if such a change would be accepted.

**Comment by patrick-mcdougle** [comment]
@NickGlenn

**Comment by NickGlenn** [comment]
@patrick-mcdougle That would be fantastic!  I had wanted to implement that as an option beforehand but unfortunately became flooded with more pressing tasks.  Hopefully I will see a PR from you this weekend.

**Comment by patrick-mcdougle** [comment]
Can I include lodash.throttle as a dependency or is that not allowed? By default it has this behavior. EDIT: nvm, this was a bad idea.

**Comment by NickGlenn** [comment]
Hi @patrick-mcdougle, I'd prefer not to include other dependencies if I can help it.  Especially libraries like Lodash where end users might be using alternatives that accomplish roughly the same goals, like Underscore, Ramda, and LazyJS.

**Comment by patrick-mcdougle** [comment]
@nickGlenn I ended up implementing in place in the util file. Check out the PR I opened. 🤓

**Comment by NickGlenn** [comment]
Thanks @patrick-mcdougle!  I will try to review and test today.
